Ejercicio3: Ejercicio3.o funcionesCola.o
	gcc -o Ejercicio3 Ejercicio3.c funcionesCola.c

Ejericicio3.o: Ejercicio3.c
	gcc -c Ejercicio3.c

funcionesCola.o: funcionesCola.c cola.h
	gcc -c funcionesCola.c

clean:
	rm -f *.o